name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/phpunit@v3
      with:
        version: latest
        php_version: latest
        configuration: phpunit.xml
